zerotier:
  id: af78bf9436630e43
  token: MyuDhfUYxCkc8eCH8cA4bt4WMgR6saWT

robot:
  url: http://localhost:6600
  client: controller

s3:
  deploy: true # True > deploy, false > use
  instance:
    farm: 'tlre'
    size: 10000
    shards: 10
    parity: 4
    shard_size: 2000
  Use:
    s3_service_name: '' # use this s3 service under the robot


